---
OperatingSystems:
  AmazonLinux2:
    AMI:
      us-west-2: ami-0e34e7b9ca0ace12d
      us-east-1: ami-09d95fab7fff3776c
      us-east-2: ami-07c8bc5c1ce9598c3
    DeviceName: "/dev/xvda"
    Type: linux
    ImageOwner: '868072565346'
    ImageOwnerName: DataDevops
  AmazonWindows2019:
    AMI:
      us-west-2: ami-029e27fb2fc8ce9d8
      us-east-1: ami-04a0ee204b44cc91a
      us-east-2: ami-0239d3998515e9ed1
    DeviceName: "/dev/sda1"
    Type: windows
    ImageOwner: '868072565346'
    ImageOwnerName: DataDevops