---
OperatingSystems:
  AmazonLinux2:
    DeviceName: "/dev/xvda"
    Type: linux
    ImageOwner: '868072565346'
    ImageOwnerName: DataDevops
  AmazonWindows2019:
    DeviceName: "/dev/sda1"
    Type: windows
    ImageOwner: '868072565346'
    ImageOwnerName: DataDevops